# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.acquisti.documentoAC.web.DocumentoAcquistoGridActionAdapter', 'it.softre.thip.acquisti.documentoAC.web.YDocumentoAcquistoGridActionAdapter', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.web.DocumentoVenditaGridActionAdapter', 'it.softre.thip.vendite.documentoVE.web.YDocumentoVenditaGridActionAdapter', '0', 'N');
